NotSoFarAway\ApiBundle\Entity\Article:
    attributes:
        id:
            groups: ['article']
        title:
            groups: ['article']
        country:
            groups: ['article']
        author:
            groups: ['article']
        publish_time:
            groups: ['article']
        content:
            groups: ['article']
        link:
            groups: ['article']
        image_src:
            groups: ['article']
        divergents:
            groups: ['article']

NotSoFarAway\ApiBundle\Entity\Author:
    attributes:
        id:
            groups: ['article','author']
        name:
            groups: ['article','author']
        website:
            groups: ['article','author']
        logo_src:
            groups: ['article','author']

NotSoFarAway\ApiBundle\Entity\Country:
    attributes:
        id:
            groups: ['article','country']
        name:
            groups: ['article','country']
        flag_src:
            groups: ['article','country']
