not_so_far_away_api:
    resource: "@NotSoFarAwayApiBundle/Controller/DefaultController.php"
    type:     annotation

articles:
  type: rest
  resource:  NotSoFarAway\ApiBundle\Controller\ArticleController

authors:
  type: rest
  resource:  NotSoFarAway\ApiBundle\Controller\AuthorController

countries:
  type: rest
  resource:  NotSoFarAway\ApiBundle\Controller\CountryController
