nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation

articles:
    type: rest
    resource:  NotSoFarAway\ApiBundle\Controller\ArticleController

authors:
    type: rest
    resource:  NotSoFarAway\ApiBundle\Controller\AuthorController

countries:
    type: rest
    resource:  NotSoFarAway\ApiBundle\Controller\CountryController
